server:
  port: 8081
  servlet:
    context-path:

spring:
  datasource:
    url: jdbc:mysql:///admin?serverTimezone=UTC  #数据库名称：admin
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper_locations: classpath:mapperXml/*.xml

